DROP TABLE IF EXISTS Pokemon_Rank;
DROP TABLE IF EXISTS Player_Challenge;
DROP TABLE IF EXISTS Ruleset;
DROP TABLE IF EXISTS Party;

DROP TABLE IF EXISTS Challenge;
DROP TABLE IF EXISTS Rule;
DROP TABLE IF EXISTS Pokemon;
DROP TABLE IF EXISTS Run;
DROP TABLE IF EXISTS Basegame;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Title;