USE `nrs`;

INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Red',1,'Kanto',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Blue',1,'Kanto',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Yellow',1,'Kanto',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Gold',2,'Johto',1);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Silver',2,'Johto',1);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Crystal',2,'Johto',1);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Ruby',3,'Hoenn',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Sapphire',3,'Hoenn',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Emerald',3,'Hoenn',3);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('FireRed',3,'Kanto',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('LeafGreen',3,'Kanto',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Diamond',4,'Sinnoh',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Pearl',4,'Sinnoh',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Platinum',4,'Sinnoh',4);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('HeartGold',4,'Johto',3);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('SoulSilver',4,'Johto',3);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Black',5,'Unova',3);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('White',5,'Unova',3);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Black 2',5,'Unova',4);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('White 2',5,'Unova',4);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('X',6,'Kalos',1);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Y',6,'Kalos',1);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Omega Ruby',6,'Hoenn',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Alpha Sapphire',6,'Hoenn',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Sun',7,'Alola',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Moon',7,'Alola',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Ultra Sun',7,'Alola',4);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Ultra Moon',7,'Alola',4);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Let''s Go Pikachu',7,'Kanto',2);
INSERT INTO `BaseGame`(`name`,`generation`,`region`,`difficulty`) VALUES ('Let''s Go Eevee',7,'Kanto',2);
