INSERT INTO Pokemon(name) VALUES ("Mega Venusaur");
INSERT INTO Pokemon(name) VALUES ("Mega Charizard X");
INSERT INTO Pokemon(name) VALUES ("Mega Charizard Y");
INSERT INTO Pokemon(name) VALUES ("Mega Blastoise");
INSERT INTO Pokemon(name) VALUES ("Mega Alakazam");
INSERT INTO Pokemon(name) VALUES ("Mega Gengar");
INSERT INTO Pokemon(name) VALUES ("Mega Kangaskhan");
INSERT INTO Pokemon(name) VALUES ("Mega Pinsir");
INSERT INTO Pokemon(name) VALUES ("Mega Gyarados");
INSERT INTO Pokemon(name) VALUES ("Mega Aerodactyl");
INSERT INTO Pokemon(name) VALUES ("Mega Mewtwo X");
INSERT INTO Pokemon(name) VALUES ("Mega Mewtwo Y");
INSERT INTO Pokemon(name) VALUES ("Mega Ampharos");
INSERT INTO Pokemon(name) VALUES ("Mega Scizor");
INSERT INTO Pokemon(name) VALUES ("Mega Heracross");
INSERT INTO Pokemon(name) VALUES ("Mega Houndoom");
INSERT INTO Pokemon(name) VALUES ("Mega Tyranitar");
INSERT INTO Pokemon(name) VALUES ("Mega Blaziken");
INSERT INTO Pokemon(name) VALUES ("Mega Gardevoir");
INSERT INTO Pokemon(name) VALUES ("Mega Mawile");
INSERT INTO Pokemon(name) VALUES ("Mega Aggron");
INSERT INTO Pokemon(name) VALUES ("Mega Medicham");
INSERT INTO Pokemon(name) VALUES ("Mega Manectric");
INSERT INTO Pokemon(name) VALUES ("Mega Banette");
INSERT INTO Pokemon(name) VALUES ("Mega Absol");
INSERT INTO Pokemon(name) VALUES ("Mega Garchomp");
INSERT INTO Pokemon(name) VALUES ("Mega Lucario");
INSERT INTO Pokemon(name) VALUES ("Mega Abomasnow");
INSERT INTO Pokemon(name) VALUES ("Mega Beedrill");
INSERT INTO Pokemon(name) VALUES ("Mega Pidgeot");
INSERT INTO Pokemon(name) VALUES ("Mega Slowbro");
INSERT INTO Pokemon(name) VALUES ("Mega Steelix");
INSERT INTO Pokemon(name) VALUES ("Mega Sceptile");
INSERT INTO Pokemon(name) VALUES ("Mega Swampert");
INSERT INTO Pokemon(name) VALUES ("Mega Sableye");
INSERT INTO Pokemon(name) VALUES ("Mega Sharpedo");
INSERT INTO Pokemon(name) VALUES ("Mega Camerupt");
INSERT INTO Pokemon(name) VALUES ("Mega Altaria");
INSERT INTO Pokemon(name) VALUES ("Mega Glalie");
INSERT INTO Pokemon(name) VALUES ("Mega Salamence");
INSERT INTO Pokemon(name) VALUES ("Mega Metagross");
INSERT INTO Pokemon(name) VALUES ("Mega Latias");
INSERT INTO Pokemon(name) VALUES ("Mega Latios");
INSERT INTO Pokemon(name) VALUES ("Mega Rayquaza");
INSERT INTO Pokemon(name) VALUES ("Mega Lopunny");
INSERT INTO Pokemon(name) VALUES ("Mega Gallade");
INSERT INTO Pokemon(name) VALUES ("Mega Audino");
INSERT INTO Pokemon(name) VALUES ("Mega Diancie");

INSERT INTO Pokemon(name) VALUES ("Deoxys-Attack");
INSERT INTO Pokemon(name) VALUES ("Deoxys-Defense");
INSERT INTO Pokemon(name) VALUES ("Deoxys-Speed");
INSERT INTO Pokemon(name) VALUES ("Hoopa-Unbound");

DELETE FROM Pokemon WHERE `name` = "Oricorio";
INSERT INTO Pokemon(name) VALUES ("Oricorio-Baile");
INSERT INTO Pokemon(name) VALUES ("Oricorio-Pom-Pom");
INSERT INTO Pokemon(name) VALUES ("Oricorio-Sensu");
INSERT INTO Pokemon(name) VALUES ("Oricorio-P'au");

INSERT INTO Pokemon(name) VALUES ("Pikachu (Cosplay)");
INSERT INTO Pokemon(name) VALUES ("Pikachu (Partner)");
INSERT INTO Pokemon(name) VALUES ("Eevee (Partner)");

UPDATE Pokemon SET `name` = 'Ninetales (Flash Fire)' WHERE `name` = 'Ninetales';
INSERT INTO Pokemon(name) VALUES ("Ninetales (Drought)");
UPDATE Pokemon SET `name` = 'Kecleon (Color Change)' WHERE `name` = 'Kecleon';
INSERT INTO Pokemon(name) VALUES ("Kecleon (Protean)");
UPDATE Pokemon SET `name` = 'Torkoal (White Smoke)' WHERE `name` = 'Torkoal';
INSERT INTO Pokemon(name) VALUES ("Torkoal (Drought)");
UPDATE Pokemon SET `name` = 'Pelipper (Keen Eye)' WHERE `name` = 'Pelipper';
INSERT INTO Pokemon(name) VALUES ("Pelipper (Drizzle)");
UPDATE Pokemon SET `name` = 'Vanilluxe (Ice Body)' WHERE `name` = 'Vanilluxe';