INSERT INTO Challenge(name, tier, classification, description) VALUES ("The Wrong Generation", "Bronze", "Multiple Runs", "Complete at least two pairs of original games and their remakes (for example, one pair could consist of Red and FireRed).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Ultimate Edition", "Bronze", "Multiple Runs", "Complete a Nuzlocke of every 'third version' game (Yellow, Crystal, Emerald, Platinum, Black 2/White 2, Ultra Sun/Ultra Moon).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Globetrotter", "Silver", "Multiple Runs", "Complete at least one Nuzlocke in every region, with each run having five deaths or fewer.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Share the Love", "Silver", "Multiple Runs", "Complete a Nuzlocke with every single starter from a generation of your choice (the starter must be on your final team and may not die).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("No Dupes!", "Gold", "Multiple Runs", "Complete at least five Nuzlockes of games that take place in the same region without ever using the same Pokemon twice.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Deja Vu", "Gold", "Multiple Runs", "Complete two runs with identical final teams, with the runs taking place in different regions.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("High-Five", "Bronze", "Single Run", "Complete a Nuzlocke with a cumulative ruleset difficulty of five or more.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("No Gods or Kings", "Bronze", "Single Run", "Complete a Nuzlocke using only Pokemon ranked B+ or below throughout the run.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Fiverr", "Bronze", "Single Run", "Complete a Nuzlocke in which you only use five team slots.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Back to Mono", "Bronze", "Single Run", "Complete a Nuzlocke without using a single dual-type Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Dual of the Fates", "Bronze", "Single Run", "Complete a Nuzlocke using only dual-type Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("New Is Always Better", "Bronze", "Single Run", "Complete a Nuzlocke using only Pokemon introduced in the region in which the game takes place (may not be done in Kanto games or Black/White).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Fair Fight", "Bronze", "Single Run", "When facing a Gym Leader, have only as many Pokemon on your team as they have on theirs.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("That Was Easy", "Silver", "Single Run", "Complete a deathless Nuzlocke of a Level 4 difficulty game.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Well, Technically...", "Silver", "Single Run", "Complete a Nuzlocke without ever using TMs, move tutors, or move reminders.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("The Four Derps of the Apocalypse", "Silver", "Single Run", "Take your starter, an early-game Bug, an early-game bird, and an early-game rodent to the Hall of Fame without any of them dying.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("The Dark Knight", "Silver", "Single Run", "In every battle against a rival that has a starter Pokemon, use your own starter to take on your opponent’s starter.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Reconstruction", "Silver", "Single Run", "Recover from losing more than half your team in a single battle by going the rest of the run without another death.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Go Fish", "Silver", "Single Run", "Complete a Nuzlocke using only Pokemon that you acquired by fishing.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Team Four Star", "Silver", "Single Run", "Complete a Nuzlocke in which you only use four team slots.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Extreme Set Mode", "Gold", "Single Run", "Complete a Nuzlocke without ever switching Pokemon out in battle.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Gotta Catch 'Em All", "Gold", "Single Run", "Successfully catch a Pokemon in every single pre-Elite Four area in the game.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Deep Blue", "Gold", "Single Run", "Complete a Nuzlocke with a rating of 3000 or higher.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Oh Heal No", "Gold", "Single Run", "Complete a Nuzlocke without using any Pokemon Centers or non-compulsory healing NPCs. In addition, Pokemon may only go in the box if they have full HP and PP and are not afflicted by any status conditions (catching Pokemon while your team is full is fine). This does not apply to the Generation I games, as the box doesn’t heal Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Unventory", "Gold", "Single Run", "Complete a Nuzlocke without using any items apart from Key Items and HMs.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Wildlife Preserver", "Gold", "Single Run", "Complete a Nuzlocke without defeating a single wild Pokemon (or catching wild Pokemon that aren’t your first encounter in an area in the Let’s Go games).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Three's a Crowd", "Gold", "Single Run", "Complete a Nuzlocke in which you only use three team slots.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Mirror Move", "Bronze", "Single Battle", "Defeat a rival, evil team boss, Gym Leader, Elite Four member, or Champion with a team identical to their own.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("You've Got a Friend in Me", "Bronze", "Single Battle", "Use your starter to sweep an Elite Four member or Champion without any setup.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Run Killer", "Silver", "Single Battle", "Defeat Ultra Necrozma in Ultra Sun or Ultra Moon without losing any team members.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Team Effort", "Silver", "Single Battle", "Use every single Pokemon on your team in the Champion battle and in every Elite Four battle.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Untouchable", "Gold", "Single Battle", "Beat the Champion with zero net HP loss and no item use during the battle (held items are fine, though). More than one Pokemon must be used in the battle.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("High Risk, Low Reward", "Gold", "Single Battle", "Sweep a Gym Leader, Elite Four member, or Champion using a Pokemon with a 4x weakness to the opponent’s chosen type (the leader must have at least one Pokemon with a damage-dealing move of their chosen type).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Brock n' Roll", "Leader", "Kanto", "Defeat Brock using only Normal-types.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Mistymeanor", "Leader", "Kanto", "Defeat Misty without using Grass-types or status moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Surge Protector", "Leader", "Kanto", "Defeat Surge without using any Pokemon that resistant or immune to Electric-type moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Amerika the Beautiful", "Leader", "Kanto", "Defeat Erika using only Water-types, excluding Gyarados.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("D.S. al koga", "Leader", "Kanto", "Yellow: Defeat Koga without missing a single move. Other Kanto Games: Defeat Koga by making at least one of his Pokemon use Self-Destruct.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Sabrina the Cheating Witch", "Leader", "Kanto", "Defeat Sabrina using only a Hitmonlee or Hitmonchan.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Blaine as Day", "Leader", "Kanto", "Defeat Blaine without a single Burn Heal in your inventory.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Don Giovanni", "Leader", "Kanto", "Sweep Giovanni with a Poison-type Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Falkner? I Barely Know 'Er!", "Leader", "Johto", "Sweep Falkner with a Zubat.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Bugsy Mogues", "Leader", "Johto", "Sweep Bugsy with a Togepi or Togetic.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Whitneysing a Murder", "Leader", "Johto", "GSC: Defeat Whitney by using Rollout. HGSS: Defeat Whitney with Pokemon that have evolved once and are level 20 or under.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Absolutely Mortyfied", "Leader", "Johto", "Defeat Morty while making at least one of his Pokemon Struggle itself to death.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("How Much Wood Would Chuck Chuck?", "Leader", "Johto", "Defeat Chuck by only using HM moves or TM moves obtained from other Gym Leaders.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Smooth Jas", "Leader", "Johto", "Defeat Jasmine with a Dark-type Pokemon or a Pokemon that has a Fairy typing in later generations.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Small Pryce to Pay", "Leader", "Johto", "Defeat Pryce with Pokemon with base stat totals less than or equal to 400.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("I Can See Clairly Now", "Leader", "Johto", "OHKO all of Clair’s Pokemon without having any of your Pokemon over level 45.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Put On the Red Light, Roxanne", "Leader", "Hoenn", "Defeat Roxanne without using any damage-dealing Water-, Grass-, or Fighting-type moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Brawlyhalla", "Leader", "Hoenn", "Defeat Brawly using only your Granite Cave catch.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Elementary, My Dear Wattson", "Leader", "Hoenn", "Defeat Wattson without a Fire-, Fighting-, or Ground-type on your team.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Flannery O'Verheat", "Leader", "Hoenn", "Defeat Flannery while keeping a Pokemon weak to Fire in battle for at least three full turns.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Where Norman Has Gone Before", "Leader", "Hoenn", "Defeat Norman by inflicting at least two of his Pokemon with (non-volatile) status conditions.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Winona Flyder", "Leader", "Hoenn", "Sweep Winona with a Grass-, Bug-, or Fighting-type.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Tater Tots and Liza Beans", "Leader", "Hoenn", "Defeat Tate and Liza using only spread moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Juan Question: What's In Your Wallace?", "Leader", "Hoenn", "Use Solarbeam to KO at least three of Juan’s/Wallace’s Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Noah's Roark", "Leader", "Sinnoh", "Defeat Roark and switch out at least three Pokemon against his Cranidos.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Gardenia of Eden", "Leader", "Sinnoh", "Defeat Gardenia using only your Eterna Forest catch.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Maylene Mean Fighting Machine", "Leader", "Sinnoh", "Defeat Maylene using only HP draining moves (all non-damaging moves are also fair game).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Wake Up, Sheeple!", "Leader", "Sinnoh", "Defeat Wake using only Pokemon you can catch in the Great Marsh and their evolutions.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Fantina of the Opera", "Leader", "Sinnoh", "Defeat Fantina using only Ghost-types.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("BYRONICLE", "Leader", "Sinnoh", "Defeat Byron without using any super effective or STAB moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Candice Day Get Any Worse?", "Leader", "Sinnoh", "Defeat Candice without using any 100% accurate moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Volknerswagen", "Leader", "Sinnoh", "Defeat Volkner using only Pokemon that appear on any of Volkner’s or Flint’s in-game teams.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Watercress Salad with Cilantro and Chili Flakes", "Leader", "Unova", "Defeat Chili, Cress, or Cilan using only your starter.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Lenora Sphere", "Leader", "Unova", "Defeat Lenora with one of your Pokemon surviving a boosted Retaliate from her Watchog (may not be in the Roggenrola line).");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Iceburgh Lettuce", "Leader", "Unova", "Defeat Burgh using only Bug-type Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Queen Elesabeth II", "Leader", "Unova", "Defeat Elesa without any of your Pokemon ever getting paralyzed.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Exclaydrill", "Leader", "Unova", "Defeat Clay without using any super effective moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Skyla White", "Leader", "Unova", "Sweep Skyla with a Pokemon weak to Flying.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Alpha Brycentauri", "Leader", "Unova", "Sweep Brycen with a Ground-type.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Dr. Drayden feat. Iris Cube", "Leader", "Unova", "Defeat Drayden or Iris without using moves that do neutral damage.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("I Think I've Found Myself a Cherenleader", "Leader", "Unova", "Defeat Cheren without using your starter or Floccesy Ranch catch.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Roxie You Like a Hurricane", "Leader", "Unova", "Defeat Roxie and get all of your Pokemon poisoned in the process.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Marlon Off-Brando", "Leader", "Unova", "Defeat Marlon with a Pokemon that can learn Shell Smash.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Rule Violation", "Leader", "Kalos", "Defeat Viola with an early-route rodent or bug.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Flagrant Foul", "Leader", "Kalos", "Defeat Grant with a fossil Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Korrina-Gadda-Da-Vida", "Leader", "Kalos", "Defeat Korrina with a Pokemon weak to Fighting.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Esperamos!", "Leader", "Kalos", "Defeat Ramos without using any moves above 60 base power.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Oh My Darlin' Clemontine", "Leader", "Kalos", "Defeat Clemont with only Flying- or Water-types.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("High Valeriean", "Leader", "Kalos", "Defeat Valerie using only Dragon-types.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("The Twelve Olympians", "Leader", "Kalos", "Defeat Olympia in exactly twelve moves.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Beowulfric", "Leader", "Kalos", "Defeat Wulfric with one Pokemon, and use only special moves against his Cryogonal and only physical moves against his Avalugg.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Hala At Your Boy", "Leader", "Alola", "Defeat Hala at the Pokemon League with a Pokemon you used against him in his kahuna battle.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Oliviability Rankings", "Leader", "Alola", "Defeat Olivia using only D Rank or E Rank Pokemon.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("Tunanudle Casserole", "Leader", "Alola", "Defeat Nanu using Pokemon you obtained by fishing.");
INSERT INTO Challenge(name, tier, classification, description) VALUES ("If You're Hapu and You Know It", "Leader", "Alola", "Defeat Hapu with Pokemon that appear in Totem Battles, whether as Totem Pokemon or assist Pokemon.");
