DELETE FROM Rule;

INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (1, "Dupes Clause", 0, "A 'dupe' (short for duplicate) is a Pokemon which appears as a first encounter but belongs to the same species as a Pokemon that has already been caught. The Dupes Clause means that if the first Pokemon encountered in an area is a dupe, the player may ignore it and catch the first non-dupe encounter instead. The motivation for this rule is to increase the variety of Pokemon on a player's team. The Dupes Clause is considered acceptable in a Nuzlocke challenge. Many variants on this rule exist: the rule may be extended to include any Pokemon belonging to the same evolutionary family as a previously caught Pokemon; for a harsher variant, if the first encounter in an area is a dupe, no Pokemon may be captured in the area; the player may get a limited number of tries to find a non-dupe.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (2, "Set Mode", 2, "Every Pokemon game has two possible ways to play: Switch Mode, which allows you to switch Pokemon after knocking out an opponent, and Set Mode, which doesn't give you this option. This makes the game more difficult as it removes the player's ability to perform perfectly safe switches. You can toggle between Shift and Set in the in-game Options menu.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (3, "Monotype", 3, "A variant on the Nuzlocke challenge in which all the Pokemon used must be of the same type. The first encounter rule is often modified so as to allow the first Pokemon of the chosen type in each area to be caught.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (4, "No items in battle", 3, "The player is not allowed to use any items during battle including healing items, X-items, etc. The use of held items is generally permitted, however.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (5, "Wedlocke", 4, "A variant on the Nuzlocke challenge based on the idea that Pokemon in the team form romantic partnerships based on the order in which they are caught. Pokemon that are partnered must fight together in 'double' battles and may not switch out in battle except with their partner. If a party Pokemon does not have a partner, the encounter rules are modified so that a Pokemon of the opposite gender must be caught next. These rules may be altered to allow or require same-sex partnerships. Wedlockes can be notoriously difficult as the player will always essentially be fighting with a team of two Pokemon.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (6, "Level limit", 1, "A maximum level allowed for the player's Pokemon when entering a Gym battle. This level is often based on either the highest-leveled or lowest-leveled Pokemon of the Gym Leader, with further adjustments being up to the player.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (7, "Superless", 4, "Super effective moves may never be used by the player's Pokemon.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (8, "STABless", 4, "STAB (same-type attack bonus) moves may never be used by the player's Pokemon. In other words, damage-dealing moves that have the same type as one of the types of the Pokemon using the move are not permitted.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (9, "Notepad", 3, "Pokemon cannot be stored in the PC. If the party is full, no additional Pokemon can be caught until a space is opened by a death. This variant is named after Notepad's runs (Freddy's Blue Nuzlocke and Freddy's Gold Nuzlocke). A less strict variant allows spare Pokemon to be captured, but not rotated into the party until one of the party Pokemon dies (see the Teamlocke). A stricter variant lets you catch six Pokemon, but does not allow them to be replaced in the event of a death.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (10, "Teamlocke", 2, "A variant in which the player is not allowed to remove living Pokemon from their party. The player is still permitted to catch Pokemon when their team is full, a feature that distinguishes Teamlockes from Notepad runs. Essentially, the PC may only be used when the player needs to replace a dead party member.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (11, "No evolution", 4, "The player is not allowed to evolve any of their Pokemon in any manner. A stricter variant disallows the player from using Pokemon that are evolved forms (for example, a Pidgeotto caught in the wild).");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (12, "No starter", 1, "The player is not allowed to use their starter or its evolutions and must replace it with their first catch.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (13, "Unlocke", 2, "The player unlocks types upon defeating Gym Leaders, often corresponding to the Gym Leader's preferred type. The player may only use Pokemon that have at least one of their types unlocked. A more difficult variant may disallow dual-typed Pokemon from being used until both of their types have been unlocked.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (14, "Alphabetlocke", 1, "A variant based on the alphabet. If the new capture in a certain area starts with a letter that comes before the first letter in another team member's name, you must replace the old team member with the new one. This can be done with Pokemon names, nicknames, or species names. For a more complex version that involves more team-switching, see the ABC-locke.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (15, "ABC-locke", 2, "Invented by Macktavious and based off of the Alphabetlocke. As explained in the rules for the Black 2 ABC-locke: 'My Pokemon shall be given nicknames starting with a randomly selected letter of the alphabet. My team shall be selected based on the alphabet. I shall have to fill my team based on their Pokemon names (e.g. Bulbasaur). The first six alphabetically will be my party. However, once I enter a new city, or defeat a gym leader, the rule changes, and Pokemon will be selected based on the first letters of their nicknames instead. The second time this happens, they will be selected based on their species name ('Seed Pokemon' for Bulbasaur), and after the third time, the cycle will rotate back to their Pokemon names.'");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (16, "No fleeing", 1, "The player is not allowed to ever flee from wild battles. Some variants also require the player to battle every trainer possible.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (17, "Blind run", 2, "Playing a game ‘blind’ means playing it for the first time without any prior knowledge and without looking anything up about the game.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (18, "Egglocke", 2, "A variant on the Nuzlocke challenge in which new Pokemon are hatched from unknown eggs rather than captured. Prior to starting the challenge, the player solicits a large number of eggs from other players. Whenever an area is reached where a catch would normally occur, the player may hatch an egg.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (19, "Wonderlocke", 2, "A variant on the Nuzlocke challenge in which new Pokémon are acquired using the Wonder Trade feature introduced in Pokémon X and Y. The player catches the first Pokémon encountered in each area, but must immediately wonder trade it for a new Pokémon. Depending on the rules used, the player may be allowed to wonder trade the Pokémon again if its level is too high.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (20, "No Exp. Share (Generation 6+)", 2, "The player must have the Exp. Share off for the duration of the game. Only applicable to Generation 6 and 7 games.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (21, "Soul link", 2, "A soul link involves two players playing games from the same region simultaneously. Pokemon caught in the same area are linked - if one player has the Pokemon on their team, the other player must as well. In addition, if a Pokemon dies, the other player’s linked Pokemon dies as well.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (22, "Team Rainbow", 1, "The player is not allowed to have any overlapping types on their team.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (23, "No grinding", 2, "The player is not allowed to grind against wild Pokemon and must avoid them or flee from them if whenever possible.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (24, "Required battles only", 3, "The player may only take part in unavoidable battles. Wild Pokemon and avoidable trainers must be avoided whenever possible.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (25, "Limited items in battle (1-3)", 2, "The player may only use a certain amount of items (for this rule, the limit must be between 1 and 3, inclusive) during battle including healing items, X-items, etc. The use of held items is generally permitted, however.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (26, "Limited items in battle (4-5)", 1, "The player may only use a certain amount of items (for this rule, the limit must be 4 or 5) during battle including healing items, X-items, etc. The use of held items is generally permitted, however.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (27, "Dupes Clause (Restrictive)", 1, "A harsher variant of the regular Dupes Clause (see above). If the first encounter in an area is a dupe, no Pokemon may be captured in the area. Alternatively the player may get a limited number of tries to find a non-dupe.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (28, "Wild Card (Difficulty 1)", 1, "Use this for a rule that you can't find on the site. A wild card rule of difficulty 1 should make the run slightly more difficult.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (29, "Wild Card (Difficulty 2)", 2, "Use this for a rule that you can't find on the site. A wild card rule of difficulty 2 should make the run more difficult.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (30, "Wild Card (Difficulty 3)", 3, "Use this for a rule that you can't find on the site. A wild card rule of difficulty 3 should make the run significantly more difficult.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (31, "Wild Card (Difficulty 4)", 4, "Use this for a rule that you can't find on the site. A wild card rule of difficulty 4 should raise the run's difficulty to a point at which the dynamic of the run changes dramatically.");
INSERT INTO Rule(rule_id, name, difficulty, description) VALUES (32, "Generationlocke", 2, "The player may only use one Pokemon from each generation on their team at a time.");

ALTER TABLE Rule AUTO_INCREMENT = 0